version: "2"
services:
  nginx-uwsgi:
    build:
      context: ./build
    volumes:
      - ../app:/srv/
      - ../../dist:/var/evernode/
    ports:
      - "80:80"
      - "443:443"
    expose:
      - "80"
      - "443"