User's Guide
------------

This part of the documentation, which is mostly prose, begins with some
background information about EverNode, then focuses on step-by-step
instructions for web development with EverNode.

.. toctree::
   :maxdepth: 2

   foreword
   installation
   getting-started
   patterns

API Reference
-------------

If you are looking for information on a specific function, class or
method, this part of the documentation is for you.

.. toctree::
   :maxdepth: 2

   api
